void launch_band_attention(float* x,
                           float* attn,
                           float* q,
                           float* k,
                           float* v,
                           int window,
                           int bs,
                           int nh,
                           int nt,
                           int channel);